### ISSUE TITLE
Save file (.sl2) path cant contain spaces

### ISSUE THREAD

**Issue by FunnyMonkeyBaz** [pawREP/ACVIEmblemCreator#12]
I currently have a problem that when i try to select the save file i get the same error as in the titeel

Path:
C:\Users\User Name\AppData\Roaming\ArmoredCore6\[My ID]

Is there a possibility of this being fixed or is this just the kinda thing that isnt really fixable

**Comment by pawREP** [comment]
The issue with spaces in save file paths is in Yabber, a dependency I'm using to (un)pack the save files. The tool is kind of old, unmaintained and fails to build for me, so trying to fix this issue is annoying. 

For now you can get around the issue by moving the save file to a folder that doesn't have any spaces in it's full path.

**Comment by pawREP** [comment]
This issue has been fixed in release v1.09
