### ISSUE TITLE
Program prompt hangs after dragging both save file and .JSONs into the EmblemCreator.exe

### ISSUE THREAD

**Issue by GraverobberJ** [pawREP/ACVIEmblemCreator#4]
No errors or progress to indicate it's running, it just opens the program window and hangs there.

**Comment by pawREP** [comment]
Thanks for the report. I suspect this might happen when you have some IO issue in the folder where your sl2 file is located. Either you have no permission to write in this folder or the save file can't be overwritten because it's in use. As a work around you could try to copy the .sl2 file to some other location, for example next to the EmblemCreator.exe and try again. I'm working on a more permanent fix and better diagnostics for this particular issue.

**Comment by skeith** [comment]
I am also having this issue and I can confirm that I have copied my sl2 file to emblem creator folder along with the json(s). I have tried several times but there is no indicator whether it's a success or not. The sl2 backup files was created but when I compared the hash between copied sl2 and original, it's still the same.

**Comment by skeith** [comment]
Found a fix!

Your emblem creator doesn't go very well with spaces in path. Eliminating spaces on folder names (path) will make the program works

**Comment by pawREP** [comment]
> Your emblem creator doesn't go very well with spaces in path. Eliminating spaces on folder names (path) will make the program works

Awesome, this is valuable info. 
I looked into the issue and it's a limitation of Yabber, the external tool we use to unpack the save files. Emblem Creator will now emit an error when save file paths with spaces are passed in. It's not a proper fix but it will allow people to troubleshoot the issue more easily until I can address the underlying cause.

**Comment by pawREP** [comment]
The issue with spaces in save file paths has been fully resolved as of release v1.09.
